server.port=${USER_SERVICE_PORT}
spring.application.name=user-service
spring.data.mongodb.uri=${USER_DB_URI}
jwt.secret=${JWT_SECRET}
jwt.access.token.expiration=${JWT_ACCESS_EXPIRATION}
security.jwt.enabled=${SECURITY_JWT_ENABLED}
logging.level.com.example.userservice=DEBUG
spring.main.allow-circular-references=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.security.enabled=false
